package common;
 
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;
 
/**
 * The table of equations in the Bazaar game: a collection of up to 10
 * equations visible to all players for the duration of a game.
 *
 * The table is chosen once at game setup and does not change. Both the
 * referee and the players consult it to determine which trades are
 * possible and which exchange requests are legal.
 *
 * Data representation:
 *   A list of up to 10 Equation values. The list is ordered, but the
 *   equations themselves are treated as an unordered set — no two
 *   equations in the table are equal.
 *
 * Invariant: the list contains 0–10 equations and has no duplicates.
 */
public class Equations {
 
    private final List<Equation> equations;
 
    // -------------------------------------------------------------------------
    // Constructor
    // -------------------------------------------------------------------------
 
    /**
     * Creates a table from the given list of equations.
     *
     * @throws IllegalArgumentException if the list contains more than 10
     *     equations
     */
    public Equations(List<Equation> equations) {
        if (equations == null || equations.size() > 10) {
            throw new IllegalArgumentException(
                "An equation table must contain 0–10 equations.");
        }
        this.equations = Collections.unmodifiableList(new ArrayList<>(equations));
    }
 
    // -------------------------------------------------------------------------
    // (1) Creating a table of equations
    // -------------------------------------------------------------------------
 
    /**
     * Returns a new table containing exactly 10 randomly generated equations.
     *
     * Each equation is generated by shuffling the five pebble colors,
     * splitting them into two non-empty disjoint groups, and sampling
     * 1–4 pebbles from each group for the two sides.
     */
    public static Equations createRandom() {
        Random rng = new Random();
        List<Equation> result = new ArrayList<>();
        while (result.size() < 10) {
            try {
                result.add(randomEquation(rng));
            } catch (IllegalArgumentException ignored) {
                // retry if random generation happens to violate a constraint
            }
        }
        return new Equations(result);
    }
 
    // -------------------------------------------------------------------------
    // (2) Filtering equations a player can use
    // -------------------------------------------------------------------------
 
    /**
     * Returns a new table containing only the equations that the player
     * can apply in at least one direction, given their wallet and the
     * bank's current supply.
     *
     * Used by a player to determine which trades are available on its turn,
     * and by the referee to validate exchange requests.
     */
    public Equations filterApplicable(Pebbles wallet, Pebbles bank) {
        List<Equation> applicable = new ArrayList<>();
        for (Equation eq : equations) {
            if (eq.canApply(wallet, bank)) {
                applicable.add(eq);
            }
        }
        return new Equations(applicable);
    }
 
    // -------------------------------------------------------------------------
    // (4) Rendering the table graphically
    // -------------------------------------------------------------------------
 
    /**
     * Returns a text representation of this equation table, listing each
     * equation on its own line with a one-based index.
     *
     * Example:
     *   Equations:
     *     1.  R W = B G
     *     2.  Y = R W B
     */
    public String render() {
        StringBuilder sb = new StringBuilder();
        sb.append("Equations:\n");
        for (int i = 0; i < equations.size(); i++) {
            sb.append(String.format("  %2d.  %s%n", i + 1, equations.get(i).render()));
        }
        return sb.toString();
    }
 
    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------
 
    /**
     * Returns a read-only view of the equations in this table.
     */
    public List<Equation> getEquations() {
        return equations;
    }
 
    /**
     * Returns the number of equations in this table.
     */
    public int size() {
        return equations.size();
    }
 
    /**
     * Returns true if this table contains no equations.
     */
    public boolean isEmpty() {
        return equations.isEmpty();
    }
 
    // -------------------------------------------------------------------------
    // Object overrides
    // -------------------------------------------------------------------------
 
    /**
     * Returns true if this table and {@code that} contain the same equations
     * in the same order.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Equations)) return false;
        Equations that = (Equations) o;
        return this.equations.equals(that.equations);
    }
 
    /**
     * Returns a hash code consistent with {@link #equals}.
     */
    @Override
    public int hashCode() {
        return equations.hashCode();
    }
 
    /**
     * Returns a text representation of this equation table.
     */
    @Override
    public String toString() {
        return render();
    }
 
    // -------------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------------
 
    /**
     * Generates one random equation by shuffling the five pebble colors,
     * splitting them into two non-empty groups, and sampling pebbles from
     * each group for the two sides.
     */
    private static Equation randomEquation(Random rng) {
        List<Pebble> colors = new ArrayList<>(List.of(Pebble.values()));
        Collections.shuffle(colors, rng);
 
        // Split at a random point — both groups must be non-empty
        int split = 1 + rng.nextInt(colors.size() - 1);
        List<Pebble> leftColors  = colors.subList(0, split);
        List<Pebble> rightColors = colors.subList(split, colors.size());
 
        Pebbles left  = randomSide(rng, leftColors);
        Pebbles right = randomSide(rng, rightColors);
        return new Equation(left, right);
    }
 
    /**
     * Builds one side of an equation by sampling 1–4 pebbles from the
     * given set of available colors, with repetition allowed.
     */
    private static Pebbles randomSide(Random rng, List<Pebble> availableColors) {
        int count = 1 + rng.nextInt(4);
        List<Pebble> side = new ArrayList<>();
        for (int i = 0; i < count; i++) {
            side.add(availableColors.get(rng.nextInt(availableColors.size())));
        }
        return new Pebbles(side);
    }
}